### ISSUE TITLE
Thank you for your application

### ISSUE THREAD

**Issue by nicped** [NikolajGO/ScreenScore#1]
Will always look at the code - so thanks for the repo.
I understand you are very new in this business

This repo has a node_modules folder with the modules required as part of the check-in - that does not look like 'best practice'. The repo does not seem to have a build script for your sass. Also I cannot see your final website from this code.

So here is a challenge: 

- Add a build script that compiles your sass to css, 
- take a look at the location of your node modules - they just be dependencies that are installed on build or with `npm install` and not be part of your actual checkin
- Create a github action that will build your site
- Publish your build to github pages

BR Nicolai

**Comment by NikolajGO** [comment]
dear Nicolai

thank you very much for your answer and your understanding. 
I have tried doing the challenges you proposed, and the site should now be published at https://nikolajgo.github.io/ScreenScore/ 

as for compiling sass to css, i hope i understand you correctly - there should already be a script in the package.json file that complies the sass files into the styles.css file in the css folder (if this is not what you meant, i will be more that happy to try again).

i have also added a README file with a bit of information on the site - as it is a work in progress project that i plan to keep working on, there are some elements still missing (e.i. the site is only partly responsively build).

if you come across any other problems, comments or challenges; again i will be happy to take them on.

thank you again

best regards
Nikolaj

**Comment by nicped** [comment]
Thanks - will take look. I missed the script in package.json - never saw that approach before, so learned something new.

Sitting in a plane and saw your site on my phone - you might want to try it on mobile device.

**Comment by NikolajGO** [comment]
i have added further responsiveness for smaller screens. it's still not perfect - i will adjust further tonight or tomorrow, when i'm able to find a bit more time.

:)
